# Definition: Configuration file for dotfile links.
# Format: TARGET -> SOURCE
#
# Sections are defined by [SET_NAME].
# Lines starting with # are comments.
# Empty lines are ignored.

[BASE]
# TERMINAL
# ghostty
~/.config/ghostty/config -> base/ghostty/config
# theme
~/.config/starship.toml -> base/starship.toml

# GIT
~/.global.gitconfig -> base/.global.gitconfig
~/.gitmessage -> base/.gitmessage
~/.config/gh/config.yml -> base/gh.yml

# TOOL
# carbon-now
~/.carbon-now.json -> base/.carbon-now.json
# editorconfig
~/.editorconfig -> base/.editorconfig
# htop
~/.config/htop/htoprc -> base/htoprc
# bat
# "~/.config/bat -> base/bat"
# ripgrep
~/.config/.ripgreprc -> base/.ripgreprc
~/.config/.rgignore -> base/.rgignore
# tealdeer
~/.config/tealdeer/config.toml -> base/tealdeer.toml
# lazygit
~/.config/lazygit/config.yml -> base/lazygit.yml
# fzf
# "~/.config/fzf -> base/fzf"
# enchant
~/.config/enchant/enchant.ordering -> base/enchant/enchant.ordering
~/.config/enchant/en_US.dic -> base/enchant/en_US.dic
# mise
~/.config/mise -> base/mise

# LANG
# js
~/.prettierrc.js -> base/.prettierrc.js
# .eslintrc.json: base/.eslintrc.json
# yaml
~/.yamllint -> base/.yamllint
# sh
~/.shellcheckrc -> base/.shellcheckrc
# cpp
~/.clang-format -> base/.clang-format
# lua
~/.config/stylua.toml -> base/stylua.toml
# python
~/.config/ruff/ruff.toml -> base/ruff.toml


[SYS_mac]
# SELF
~/.gitconfig -> mac/.gitconfig
~/.gitignore -> mac/.gitignore
# py
# "$DOTCACHE/requirements.txt -> mac/requirements.txt"

# pnpm
$DOTCACHE/Pnpmfile -> mac/Pnpmfile

# # npm
# "$DOTCACHE/Npmfile -> mac/Npmfile"

# git-cliff
# "~/Library/Application\ Support/git-cliff/cliff.toml -> base/cliff.toml"

#lsp
~/.config/rassumfrassum -> mac/rassumfrassum


[SYS_linux]
~/.gitconfig -> linux/.gitconfig
# py
# "$DOTCACHE/requirements.txt -> linux/requirements.txt"
# pnpm
$DOTCACHE/Pnpmfile -> linux/Pnpmfile


[SYS_win]
# Empty for now, but kept for consistency


[home_air15]
# zsh
~/.zshenv -> home_air15/zsh/.zshenv
$DOTCACHE/.zsh_history -> home_air15/zsh/.zsh_history
$DOTCACHE/init.zsh -> home_air15/zsh/init.zsh

# brew
$DOTCACHE/Brewfile -> home_air15/Brewfile

# ssh
~/.ssh/config -> home_air15/ssh_config
