# Definition: Configuration file for dotfile links.
# Format: TARGET -> SOURCE
#
# Sections are defined by [SET_NAME].
# Lines starting with # are comments.
# Empty lines are ignored.

[BASE]
# TERMINAL
# ghostty
# ~/.config/ghostty/config -> base/ghostty/config

# kitty
~/.config/kitty -> base/kitty

# theme
~/.config/starship.toml -> base/starship.toml

# vim
~/.vimrc -> base/.vimrc

# GIT
~/.global.gitconfig -> base/.global.gitconfig
~/.gitmessage -> base/.gitmessage
~/.gitignore -> base/.gitignore

# gh
~/.config/gh/config.yml -> base/gh.yml

# TOOL
# carbon-now
~/.carbon-now.json -> base/.carbon-now.json

# ripgrep
~/.config/rg/.ripgreprc -> base/.ripgreprc
~/.config/rg/.rgignore -> base/.rgignore
# tealdeer
~/.config/tealdeer/config.toml -> base/tealdeer.toml
# lazygit
~/.config/lazygit/config.yml -> base/lazygit.yml
# pnpm
$DOTCACHE/Pnpmfile -> base/Pnpmfile

# enchant
~/.config/enchant/enchant.ordering -> base/enchant/enchant.ordering
~/.config/enchant/en_US.dic -> base/enchant/en_US.dic
# mise
~/.config/mise -> base/mise

# git-cliff
~/.config/cliff.toml -> base/cliff.toml

# LANG
# js
~/.prettierrc.js -> base/.prettierrc.js
# .eslintrc.json: base/.eslintrc.json
# yaml
~/.yamllint -> base/.yamllint
# sh
~/.shellcheckrc -> base/.shellcheckrc
# cpp
~/.clang-format -> base/.clang-format
# lua
~/.config/stylua.toml -> base/stylua.toml
# python
~/.config/ruff/ruff.toml -> base/ruff.toml

[SYS_mac]
~/.gitconfig -> mac/.gitconfig

[SYS_linux]
~/.gitconfig -> linux/.gitconfig

[SYS_win]
# Empty for now, but kept for consistency

[home_air15]
# zsh
~/.zshenv -> home_air15/zsh/.zshenv
$DOTCACHE/.zsh_history -> home_air15/zsh/.zsh_history
$DOTCACHE/init.zsh -> home_air15/zsh/init.zsh

# brew
$DOTCACHE/Brewfile -> home_air15/Brewfile

# ssh
~/.ssh/config -> home_air15/ssh_config
