[settings]
experimental = true
disable_hints = ["*"]
idiomatic_version_file_enable_tools = ["python"]

[tools]
go     = "1.23.3"
lua = "5.4.7"
deno   = "latest"
bun = "latest"
zig    = "latest"
usage  = "latest"
